#yaml-language-server: $schema=../../generate-schemas/schemas/system.schema.json
apiVersion: canaries.flanksource.com/v1
kind: Topology
metadata:
  name: test-topology-property-merge
spec:
  schedule: "@every 10m"
  components:
    - name: root
      icon: server
      owner: infra
      components:
        - name: RootComponents
          type: virtual
          icon: server
          lookup:
            http:
              - endpoint: https://httpbin.demo.aws.flanksource.com/status/200
                name: http-lookup
                display:
                  expr: |
                    [
                      {
                        'name': 'component-a',
                        'type': 'API',
                        'properties': [{'name': 'error_percentage', 'min': 0, 'max': 100}, {'name': 'owner'}]
                      },
                      {
                        'name': 'component-b',
                        'type': 'Frontend',
                        'properties': [{'name': 'error_percentage', 'min': 0, 'max': 100}, {'name': 'owner'}]
                      },
                      {
                        'name': 'component-c',
                        'type': 'Database',
                        'properties': [{'name': 'error_percentage', 'min': 0, 'max': 100}, {'name': 'owner'}]
                      },
                    ].marshalJSON()
          properties:
            - name: error_percentage
              lookup:
                http:
                - endpoint: https://httpbin.demo.aws.flanksource.com/status/200
                  name: error_percentage_lookup
                  display:
                    expr: |
                      [
                        {
                          'name': 'component-a',
                          'properties': [{'name': 'error_percentage', 'value': 1}]
                        },
                        {
                          'name': 'component-b',
                          'properties': [{'name': 'error_percentage', 'value': 10}]
                        },
                        {
                          'name': 'component-c',
                          'properties': [{'name': 'error_percentage', 'value': 50}]
                        },
                      ].marshalJSON()
            - name: owner
              lookup:
                http:
                - endpoint: https://httpbin.demo.aws.flanksource.com/status/200
                  name: owner_lookup
                  display:
                    expr: |
                      [
                        {
                          'name': 'component-a',
                          'properties': [{'name': 'owner', 'text': 'team-a'}]
                        },
                        {
                          'name': 'component-b',
                          'properties': [{'name': 'owner', 'text': 'team-b'}]
                        },
                        {
                          'name': 'component-c',
                          'properties': [{'name': 'owner', 'text': 'team-b'}]
                        },
                      ].marshalJSON()
            - name: generic
              lookup:
                http:
                - endpoint: https://httpbin.demo.aws.flanksource.com/status/200
                  name: generic_lookup
                  display:
                    expr: |
                      [
                        {'name': 'company', 'text': 'Acme'},
                        {'name': 'location', 'text': 'Mars'},
                      ].marshalJSON()
