apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: canary-checker
resources:
  - ./base
  - ./namespace.yaml
  - ./deploy/crd.yaml
images:
  - name: controller
    newName: docker.io/flanksource/canary-checker
    newTag: latest
