apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-system
resources:
- ./base
- ./namespace.yaml
- ./crd.yaml
images:
- name: controller
  newName: docker.io/flanksource/canary-checker
  newTag: latest
