name: Publish Binary
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.12.0
    steps:
      - uses: actions/checkout@master
      - run: ./release.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
