name: Publish Docs
on:
  push:
    branches:
      - master
jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:v0.12.0
    steps:
      - uses: actions/checkout@master
      - run: make static build-api-docs build-docs deploy-docs
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
