name: Lint
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.go"
      - "Makefile"
      - "**.yaml"
      - '**.yml'
      - '**/github/workflows/lint.yml'
      - '**/.eslint*'
      - '**/package.json'
      - 'Makefile'
      - '**.jsx?'
      - '**.tsx?'
  pull_request:
    paths:
      - "**.go"
      - "Makefile"
      - "**.yaml"
      - '**.yml'
      - '**/github/workflows/lint.yml'
      - '**/.eslint*'
      - '**/package.json'
      - 'Makefile'
      - '**.jsx?'
      - '**.tsx?'
jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:15.14-alpine
    steps:
      - uses: actions/checkout@master
      - run: npm ci
        working-directory: ./ui
      - run: npm run lint:eslint
        working-directory: ./ui
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Check auto-generated files
        env:
          CI: false
        run: |
          mkdir -p ui/build
          touch ui/build/noop
          make resources
          git diff
          changed_files=$(git status -s)
          [[ -z "$changed_files" ]] ||  (printf "Change is detected in some files: \n$changed_files\n Did you run 'make resources' before sending the PR?" && exit 1)
