on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
        k8s:
          - v1.18.6
          - v1.20.7
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Test
        env:
          KUBERNETES_VERSION: ${{matrix.k8s}}
        run: ./test/e2e.sh
---
on:
 schedule:
   - cron: '0 10 * * *'
name: Cron Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
        k8s:
          - v1.18.6
          - v1.20.7
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Test
        env:
          KUBERNETES_VERSION: ${{matrix.k8s}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TEST_FOLDER: fixtures-cron
        run: ./test/e2e.sh
