on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - "**.go"
      - "Makefile"
      - "**.yaml"
      - "**.yml"
      - "test/**"
  pull_request:
    paths:
      - "**.go"
      - "Makefile"
      - "**.yaml"
      - "**.yml"
      - "test/**"
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        suite:
          - minimal
          - k8s
          - datasources
          - quarantine
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - run: make bin
      - name: Test
        env:
          KUBERNETES_VERSION: v1.20.7
        run: ./test/e2e.sh fixtures/${{matrix.suite}}
